Game:
    DefaultState: !GameState Menu
    Verbosity: !Verbosity High
Display:
    Fullscreen: false
    Height: 720
    Width: 1280
    FieldOfView: 90
    NearPlane: 0.01
    FarPlane: 1000
Graphics:
    BackfaceCulling: true
    VSync: false
Physics:
    Gravity: !Vector3 0.0 -10.0 0.0
UserInterface:
    FilePath: "/UI/index.html"
    Scale: !Vector2 1.0 1.0
