#Game:
#    ServerIP: 127.0.0.1
Display:
    Fullscreen: false
    Height: 1000
    Width: 1777
Graphics:
    BackfaceCulling: true
    VSync: false
Physics:
    Gravity: [ 0.0, -10.0, 0.0 ]
UserInterface:
    FilePath: "ingameUI.html"
    Scale: [ 1.0, 1.0 ]
Logging:
    FilePath: "dash.log"
    Debug:
        OutputVerbosity: info
        LoggingVerbosity: info
    Release:
        OutputVerbosity: error
        LoggingVerbosity: error
Editor:
    Port: 8008
