Game:
    ServerIP: 127.0.0.1
Display:
    Fullscreen: false
    Height: 720
    Width: 1280
Graphics:
    BackfaceCulling: true
    VSync: false
Physics:
    Gravity: !Vector3 0.0 -10.0 0.0
UserInterface:
    FilePath: "ingameUI.html"
    Scale: !Vector2 1.0 1.0
Logging:
    FilePath: "dash.log"
    Debug:
        OutputVerbosity: !Verbosity High
        LoggingVerbosity: !Verbosity High
    Release:
        OutputVerbosity: !Verbosity Medium
        LoggingVerbosity: !Verbosity Medium
