Up:
    Keyboard: W
Down:
    Keyboard: S
Left:
    Keyboard: A
Right:
    Keyboard: D
LookLeft:
    Keyboard: Q
LookRight:
    Keyboard: E
QuitToDesktop:
    Keyboard: Delete
ConnectToServer:
    Keyboard: R
EndTurn:
    Keyboard: T
Enter:
    Keyboard: Space
Back:
    Keyboard: Escape
ResetGame:
    Keyboard: F5
ResetCamera:
    Keyboard: F9
LoadCTF:
    Keyboard: C
LoadDeathmatch:
    Keyboard: V
