Up:
    - !Keyboard W
Down:
    - !Keyboard S
Left:
    - !Keyboard A
Right:
    - !Keyboard D
LookUp:
    - !Keyboard I
LookDown:
    - !Keyboard K
LookLeft:
    - !Keyboard J
LookRight:
    - !Keyboard L
Enter:
    - !Keyboard Return
Enter2:
    - !Keyboard Space
Back:
    - !Keyboard Backspace
