Up:
    Keyboard: W
Down:
    Keyboard: S
Left:
    Keyboard: A
Right:
    Keyboard: D
LookLeft:
    Keyboard: Left
LookRight:
    Keyboard: Right
ZoomIn:
    Keyboard: Up
ZoomOut:
    Keyboard: Down
ResetCamera:
    Keyboard: Delete
EndTurn:
    Keyboard: T
Enter:
    Keyboard: Space
Back:
    Keyboard: Backspace
ResetGame:
    Keyboard: F5
