Up:
    - !Keyboard W
Down:
    - !Keyboard S
Left:
    - !Keyboard A
Right:
    - !Keyboard D
LookUp:
    - !Keyboard I
    - !Keyboard Up
LookDown:
    - !Keyboard K
    - !Keyboard Down
LookLeft:
    - !Keyboard J
    - !Keyboard Left
LookRight:
    - !Keyboard L
    - !Keyboard Right
ZoomIn:
    - !Keyboard Up
ZoomOut:
    - !Keyboard Down
ResetCamera:
    - !Keyboard Delete
EndTurn:
    - !Keyboard T
Enter:
    - !Keyboard Space
Back:
    - !Keyboard Backspace
ResetGame:
    - !Keyboard F5