Up:
    - !Keyboard W
Down:
    - !Keyboard S
Left:
    - !Keyboard A
Right:
    - !Keyboard D
LookUp:
    - !Keyboard I
    - !Keyboard Up
LookDown:
    - !Keyboard K
    - !Keyboard Down
LookLeft:
    - !Keyboard J
    - !Keyboard Left
LookRight:
    - !Keyboard L
    - !Keyboard Right
ZoomUp:
    - !Keyboard N
ZoomDown:
    - !Keyboard M
Enter:
    - !Keyboard Space
Back:
    - !Keyboard Backspace
